### ISSUE TITLE
The Download link is not accessible

### ISSUE THREAD

**Issue by hemche** [eBay/xeazy#1]
The Download [link](https://github.corp.ebay.com/eBayMobileQuality/xeazy/blob/master/src/dist) for xeasy tool is not accessible. 
As an alternative, it would be helpful if we can know the process about how to build form Source.

**Comment by elango842003** [comment]
src/dist - you can clone this project and go to "src/dist" to goto download the binary. working on the update to read me file and push the changes soon. thank you!
